### ISSUE TITLE
Is this still under development?

### ISSUE THREAD

**Issue by bradleyess** [antonbabenko/dynamic-tfvars#1]
Hi Anton - thank you for making this! It solves a huge problem for us where we would like to use `get_output()` in our `terragrunt.hcl` files.

I am curious whether or not this project is still being developed and whether we can start to use this at our company - we would be happy to assist in development.

**Comment by antonbabenko** [comment]
Hi Bradley,

This project is in alpha, but usable for some of my customers already. I am currently on vacation and will be back to development of it from end of August.

I have done few improvements in code, which I will commit and then it should be very close for public usage and contributions. 

Best regards,
Anton.

26 лип. 2019 р. о 10:14 Bradley <notifications@github.com> пише:

**Comment by antonbabenko** [comment]
I have decided to not continue active development of this project because it has become possible to achieve the same using Terragrunt natively since [v0.19.20](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.20), which was released 15th of August 2019. 

Read [Passing outputs between modules](https://github.com/gruntwork-io/terragrunt#passing-outputs-between-modules) for more details.

I will focus my time as open-source developer on [terraform-aws-modules](https://github.com/terraform-aws-modules) and [modules.tf](https://github.com/antonbabenko/modules.tf-lambda).
