### ISSUE TITLE
Support for terragrunt 0.19.0+

### ISSUE THREAD

**Issue by neelakansha85** [antonbabenko/dynamic-tfvars#2]
Hi Anton,

A big thank you for making this! Really appreciate since I was looking for something like this to help solve dependency issue with my terragrunt modules. 

I was trying to work with terragrunt 0.19.0+ and it seems like due to the introduction of new `terragrunt.hcl` and change in format of passing values to variables using `input {...}` within `terragrunt.hcl` file as opposed to using `terraform.tfvars` this plugin is unable to execute. Below is output of the logs:

```
[terragrunt] 2019/08/08 10:50:59 Executing hook: update_dynamic_values_in_tfvars
[terragrunt] 2019/08/08 10:50:59 Running command: tfvars-annotations /Users/shah/git/infrastructure-setup/sandbox/us-east-1/eks-cluster
time="2019-08-08T10:50:59-04:00" level=info msg="Working dir:  /Users/shah/git/infrastructure-setup/sandbox/us-east-1/eks-cluster/.terragrunt-cache/4d5Ym7P6QxByxVn4DVyZ4xg9NW8/vo8pQqWUeCu_1_TBy7LGvx51SW0"
time="2019-08-08T10:50:59-04:00" level=info msg="Processing file: /Users/shah/git/infrastructure-setup/sandbox/us-east-1/eks-cluster/terraform.tfvars"
time="2019-08-08T10:50:59-04:00" level=info
time="2019-08-08T10:50:59-04:00" level=fatal msg="Can't read file: open /Users/shah/git/infrastructure-setup/sandbox/us-east-1/eks-cluster/terraform.tfvars: no such file or directory"
```

**Comment by antonbabenko** [comment]
Hi Neel!

I am glad that I am not alone who need this :)

I am on vacation and planning to continue working on this project at the end of August.

**Comment by neelakansha85** [comment]
Thanks for the update Anton.

Hope you are enjoying your vacation! 😄

**Comment by antonbabenko** [comment]
I have decided to not continue active development of this project because it has become possible to achieve the same using Terragrunt natively since [v0.19.20](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.20), which was released 15th of August 2019. 

Read [Passing outputs between modules](https://github.com/gruntwork-io/terragrunt#passing-outputs-between-modules) for more details.

I will focus my time as open-source developer on [terraform-aws-modules](https://github.com/terraform-aws-modules) and [modules.tf](https://github.com/antonbabenko/modules.tf-lambda).
